"""
Mock generator for testing and development.

This module provides a simple implementation of BaseGenerator that creates
basic geometric shapes. Useful for testing the infrastructure without
requiring AI models.
"""

import trimesh
import logging

from .base_generator import BaseGenerator

logger = logging.getLogger(__name__)


class MockGenerator(BaseGenerator):
    """
    Mock 3D generator that creates simple geometric shapes.

    This generator creates basic watertight shapes (box, sphere, cylinder)
    for testing purposes. It does not use AI models and is fast and reliable.
    Useful for development and testing the processing pipeline.

    Attributes:
        shape: Type of shape to generate ('box', 'sphere', 'cylinder').
        size_mm: Size of the shape in millimeters (default: 50mm).

    Example:
        >>> from pathlib import Path
        >>> gen = MockGenerator(shape='box', size_mm=100)
        >>> result = gen.generate("a cube", Path("outputs/cube.stl"))
        >>> print(result["success"])  # True
        >>> print(result["is_watertight"])  # True
    """

    def __init__(self, shape: str = "box", size_mm: float = 50.0) -> None:
        """
        Initialize the mock generator.

        Args:
            shape: Type of shape to generate. Options:
                  - 'box': Cube with equal dimensions
                  - 'sphere': Perfect sphere
                  - 'cylinder': Cylinder with height = diameter
            size_mm: Size of the shape in millimeters.
                    For box: edge length
                    For sphere: diameter
                    For cylinder: diameter (height = diameter)

        Raises:
            ValueError: If shape is not one of the supported types.
        """
        if shape not in ("box", "sphere", "cylinder"):
            raise ValueError(
                f"Unsupported shape: '{shape}'. "
                f"Must be one of: box, sphere, cylinder"
            )

        self.shape = shape
        self.size_mm = size_mm
        logger.info(
            f"Initialized MockGenerator with shape='{shape}', " f"size={size_mm}mm"
        )

    def _generate_raw(self, prompt: str) -> trimesh.Trimesh:
        """
        Generate a simple geometric shape.

        Creates a basic watertight mesh based on the configured shape type.
        The prompt parameter is ignored in this mock implementation.

        Args:
            prompt: Text prompt (ignored in mock implementation).

        Returns:
            A watertight Trimesh object of the configured shape.

        Note:
            All shapes generated by this method are guaranteed to be
            watertight, as they use Trimesh's built-in primitive creation.
        """
        logger.debug(
            f"Generating {self.shape} with size {self.size_mm}mm "
            f"(prompt ignored: '{prompt}')"
        )

        if self.shape == "box":
            mesh = trimesh.creation.box(
                extents=[self.size_mm, self.size_mm, self.size_mm]
            )
        elif self.shape == "sphere":
            radius = self.size_mm / 2.0
            mesh = trimesh.creation.icosphere(subdivisions=3, radius=radius)
        elif self.shape == "cylinder":
            radius = self.size_mm / 2.0
            height = self.size_mm
            mesh = trimesh.creation.cylinder(radius=radius, height=height)

        logger.debug(
            f"Generated {self.shape}: "
            f"{len(mesh.vertices)} vertices, "
            f"{len(mesh.faces)} faces, "
            f"watertight={mesh.is_watertight}"
        )

        return mesh
